SELECT DISTINCT
  ucla_bibtext_vw.bib_id
, ucla_bibtext_vw.author
, ucla_bibtext_vw.title
,ITEM_TYPE.ITEM_TYPE_NAME
,ITEM_STATUS_type.Item_status_desc
, item_barcode.item_barcode
, mfhd_item.item_enum
 
FROM MFHD_MASTER
INNER JOIN LOCATION ON MFHD_MASTER.LOCATION_ID = LOCATION.LOCATION_ID
INNER JOIN MFHD_ITEM ON MFHD_MASTER.MFHD_ID = MFHD_ITEM.MFHD_ID
INNER JOIN BIB_MFHD ON MFHD_MASTER.MFHD_ID = BIB_MFHD.MFHD_ID
INNER JOIN ucla_bibtext_vw ON BIB_MFHD.BIB_ID = ucla_bibtext_vw.BIB_ID
left outer JOIN LINE_ITEM ON ucla_bibtext_vw.BIB_ID = LINE_ITEM.BIB_ID
left outer JOIN PURCHASE_ORDER ON LINE_ITEM.PO_ID = PURCHASE_ORDER.PO_ID AND purchase_order.po_number like 'LAW%'
left outer JOIN MFHD_ITEM ON MFHD_MASTER.MFHD_ID = MFHD_ITEM.MFHD_ID
left outer JOIN ITEM ON MFHD_ITEM.ITEM_ID = ITEM.ITEM_ID
left outer JOIN ITEM_BARCODE ON ITEM.ITEM_ID = ITEM_BARCODE.ITEM_ID
left outer JOIN ITEM_TYPE ON ITEM.ITEM_TYPE_ID = ITEM_TYPE.ITEM_TYPE_ID
left outer JOIN ITEM_STATUS ON ITEM.ITEM_ID = ITEM_STATUS.ITEM_ID
left outer JOIN ITEM_STATUS_TYPE ON ITEM_STATUS.ITEM_STATUS = ITEM_STATUS_TYPE.ITEM_STATUS_TYPE
INNER JOIN CIRCCHARGES_VW cc ON MFHD_MASTER.MFHD_ID = cc.MFHD_ID

WHERE location.location_code = 'lwtrr'
      
ORDER BY ucla_bibtext_vw.title
