
REM VGER_SUPPORT UCLADB_RESERVE_TRANS

  CREATE TABLE "VGER_SUPPORT"."UCLADB_RESERVE_TRANS" 
   (	"CIRC_TRANSACTION_ID" NUMBER, 
	"ITEM_ID" NUMBER, 
	"ON_RESERVE" CHAR(1), 
	"MONTH" CHAR(6), 
	"RES_ID" NUMBER NOT NULL ENABLE
   ) ;
 CREATE UNIQUE INDEX "VGER_SUPPORT"."IX_UCLADB_RESERVE_TRANS_RES_ID" ON "VGER_SUPPORT"."UCLADB_RESERVE_TRANS" ("RES_ID") 
  ;
  ALTER TABLE "VGER_SUPPORT"."UCLADB_RESERVE_TRANS" ADD CONSTRAINT "UCLADB_CIRC_TRANS_ITEMS_PK" PRIMARY KEY ("RES_ID") ENABLE;
 
REM VGER_SUPPORT IX_U_RESERVE_TRANS_TID

  CREATE INDEX "VGER_SUPPORT"."IX_U_RESERVE_TRANS_TID" ON "VGER_SUPPORT"."UCLADB_RESERVE_TRANS" ("CIRC_TRANSACTION_ID") 
  ;
 
REM VGER_SUPPORT IX_UCLADB_RESERVE_TRANS_RES_ID

  CREATE UNIQUE INDEX "VGER_SUPPORT"."IX_UCLADB_RESERVE_TRANS_RES_ID" ON "VGER_SUPPORT"."UCLADB_RESERVE_TRANS" ("RES_ID") 
  ;
 