--USE THIS LW 9/2017

SELECT  DISTINCT
ITEM_BARCODE.ITEM_BARCODE,
PATRON_BARCODE.PATRON_BARCODE,
 patron_group.patron_group_name,
--CIRC_TRANSACTIONS.CHARGE_DATE --AS due_date
TO_CHAR(CIRC_TRANSACTIONS.CHARGE_DATE,'fmMM/ DD/ YYYY') AS due_date


FROM ITEM
INNER JOIN ITEM_BARCODE ON ITEM.ITEM_ID = ITEM_BARCODE.ITEM_ID
INNER JOIN CIRC_TRANSACTIONS ON ITEM.ITEM_ID = CIRC_TRANSACTIONS.ITEM_ID
INNER JOIN PATRON ON CIRC_TRANSACTIONS.PATRON_ID = PATRON.PATRON_ID
INNER JOIN PATRON_BARCODE ON PATRON.PATRON_ID = PATRON_BARCODE.PATRON_ID
INNER JOIN PATRON_GROUP ON CIRC_TRANSACTIONS.PATRON_GROUP_ID = PATRON_GROUP.PATRON_GROUP_ID
INNER JOIN ITEM_TYPE ON ITEM.ITEM_TYPE_ID = ITEM_TYPE.ITEM_TYPE_ID
INNER JOIN BIB_TEXT
INNER JOIN LOCATION
INNER JOIN MFHD_MASTER ON LOCATION.LOCATION_ID = MFHD_MASTER.LOCATION_ID
INNER JOIN BIB_MFHD ON MFHD_MASTER.MFHD_ID = BIB_MFHD.MFHD_ID ON BIB_TEXT.BIB_ID = BIB_MFHD.BIB_ID
INNER JOIN ITEM_VW ON MFHD_MASTER.MFHD_ID = ITEM_VW.MFHD_ID ON ITEM.ITEM_ID = ITEM_VW.ITEM_ID

WHERE      bib_text.LANGUAGE = 'jpn'
         --  AND bib_format = 'am'
           AND patron_group.patron_group_name LIKE 'IL%'
           AND CIRC_TRANSACTIONS.CHARGE_DATE between '30/JUN/2019' AND '01/JUL/2020'


--(ITEM_TYPE.ITEM_TYPE_CODE = 'illnr2' Or ITEM_TYPE.ITEM_TYPE_CODE = 'illnr4' Or ITEM_TYPE.ITEM_TYPE_CODE = 'illnr12' Or ITEM_TYPE.ITEM_TYPE_CODE = 'ill')
--AND PATRON_BARCODE.BARCODE_STATUS = '1'

--AND CIRC_TRANSACTIONS.CHARGE_DATE BETWEEN TRUNC(SYSDATE - 1) AND TRUNC(SYSDATE))

--Ara, heb, per, kur, syr, tur, uzb, uig,kaz, kir,tgk, tuk, arc, arm

ORDER BY TO_CHAR(CIRC_TRANSACTIONS.CHARGE_DATE,'fmMM/ DD/ YYYY')
          --CIRC_TRANSACTIONS.CHARGE_DATE
